[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
gocyptowa = "BgVCaSj3YyfAxnDJZ4YrBag7CCTc8fPPqY7NEr9sh9Cr"
[programs.devnet]
gocyptowa = "BgVCaSj3YyfAxnDJZ4YrBag7CCTc8fPPqY7NEr9sh9Cr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
