[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
gocyptowa = "GZ5WFnojWrqmvkUq75xZkTbvL4kAkvPFJA3pvHX5fv8K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
